change: metric data save in data-layer
STCLab-Inc/wave-autoscale pull request #185
Opened 2023-10-24 02:26 UTC by Ari-suhyeon

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] DevOps process (non-breaking change which improves efficiency and reliability for CI/CD)
- [ ] Documentation only

## What this PR does / why we need it:

Metric data save in memory (daya-layer)
- As-Is: metric data save in database
- default buffer: 500MB
- SourceMetrics add item: create_dt
- add error logs

## Which issue/s this PR fixes

fixes #183 

## How Has This Been Tested?

* moon run tested - check the buffer size of stored data
* Unit Test has been tested.

## Checklist:

2023-10-31 04:20 UTC, pueding requested changes

2023-10-31 04:20 UTC, pueding commented on core/data-layer/src/data_layer.rs
> +        }
```suggestion
loop {
    // check size :: buffersize - total size < 0 (None) => remove target data
    if metric_buffer_size_kb
        .checked_sub(subtract_total_size as u64)
        .is_some() {
        break;
    }
    let Some(front_source_metrics_metadata) = source_metrics_metadata.pop_front() else {
        break;
    };
    subtract_total_size -= front_source_metrics_metadata.2; // oldest metadata size
    remove_target_data.append(&mut vec![front_source_metrics_metadata]);
}
```

2023-10-31 04:20 UTC, pueding commented on core/data-layer/src/data_layer.rs
> +                let Some(metric_id_data) = source_metrics.get_mut(metric_id) else {
```suggestion
    let Some(source_metrics_map) = source_metrics.get_mut(metric_id) else {
```

to match variable names as shown below (source_metrics_map)

2023-10-31 04:20 UTC, pueding commented on core/data-layer/src/data_layer.rs
> +                let mut metric_id_map = BTreeMap::new();
```suggestion
    let mut source_metrics_map = BTreeMap::new();
```
In order to match variable names as shown above

2023-10-31 04:20 UTC, pueding commented on core/data-layer/src/data_layer.rs
> +    }
do not clone the original data structure that could occupy a significant amount of memory

2023-10-31 04:20 UTC, pueding commented on core/data-layer/src/data_layer.rs
> +        Ok(source_metrics_metadata.clone())
do not clone the original data

2023-10-31 04:29 UTC, pueding commented on core/data-layer/src/data_layer.rs
> +        Ok(source_metrics.clone())
```suggestion
let source_metrics = self.source_metrics_data.source_metrics.clone();
Ok(source_metrics)
```

2023-11-02 14:22 UTC, pueding commented on core/data-layer/src/data_layer.rs
> +                return DataLayer {
I think we should do panic here because it cannot get the static variable

2023-11-02 14:29 UTC, pueding commented on core/wave-autoscale/src/scaling_planner/mod.rs
> +        .unwrap_or("latest".to_string());
manage the stats as an enum type for later
```
enum Stats {
    Latest, 
    Average,
    ....
}
```

2023-11-03 00:12 UTC, Ari-suhyeon commented on core/data-layer/src/data_layer.rs
> +            DEFAULT_METRIC_BUFFER_SIZE_KB * 1000
It means KB unit convert by Byte unit

2023-11-03 03:42 UTC, pueding approved these changes

2023-11-03 03:42 UTC, merged